#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.

# Free the zoo!
if [[ -n "$MIGRATE_URL" ]]; then
    echo "---> Migrating database..."
    python wsgi.py migrate
fi